<div style="background-color: #F2F3F4; padding: 20px; border-radius: 10px;">
    <p style="font-size: 24px; font-family: 'Verdana'; color: #3A405A; text-align: center;">
Welcome to this notebook!</p>
</div>

<b><span style="color: #5F5F5F; background-color: #F2F4F2; padding: 20px; font-size: 18px; border-left: 8px solid #A9A9A9"> 📌 Importing libraries </span></b>

In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sn

import plotly.express as px

<b><span style="color: #5F5F5F; background-color: #F2F4F2; padding: 20px; font-size: 18px; border-left: 8px solid #A9A9A9">📌 Loading the csv file</span></b>

In [2]:
df=pd.read_csv('/kaggle/input/indian-agriculture-dataset/ICRISAT-District Level Data.csv')

<b><span style="color: #5F5F5F; background-color: #F2F4F2; padding: 20px; font-size: 18px; border-left: 8px solid #A9A9A9">📌 Showing first five rows</span></b>

In [3]:
df.head()

,Dist Code,Year,State Code,State Name,Dist Name,RICE AREA (1000 ha),RICE PRODUCTION (1000 tons),RICE YIELD (Kg per ha),WHEAT AREA (1000 ha),WHEAT PRODUCTION (1000 tons),...,SUGARCANE YIELD (Kg per ha),COTTON AREA (1000 ha),COTTON PRODUCTION (1000 tons),COTTON YIELD (Kg per ha),FRUITS AREA (1000 ha),VEGETABLES AREA (1000 ha),FRUITS AND VEGETABLES AREA (1000 ha),POTATOES AREA (1000 ha),ONION AREA (1000 ha),FODDER AREA (1000 ha)
0,1,1966,14,Chhattisgarh,Durg,548.0,185.0,337.59,44.0,20.0,...,1777.78,0.0,0.0,0.0,5.95,6.64,12.59,0.01,0.60,0.47
1,1,1967,14,Chhattisgarh,Durg,547.0,409.0,747.71,50.0,26.0,...,1500.00,0.0,0.0,0.0,5.77,7.24,13.02,0.01,0.56,1.23
2,1,1968,14,Chhattisgarh,Durg,556.3,468.0,841.27,53.7,30.0,...,1000.00,0.0,0.0,0.0,5.41,7.40,12.81,0.10,0.58,1.02
3,1,1969,14,Chhattisgarh,Durg,563.4,400.8,711.40,49.4,26.5,...,1900.00,0.0,0.0,0.0,5.52,7.16,12.69,0.01,0.56,0.84
4,1,1970,14,Chhattisgarh,Durg,571.6,473.6,828.55,44.2,29.0,...,2000.00,0.0,0.0,0.0,5.45,7.19,12.64,0.02,0.52,0.42

<b><span style="color: #5F5F5F; background-color: #F2F4F2; padding: 20px; font-size: 18px; border-left: 8px solid #A9A9A9">📌 Showing last five rows :</span></b>

In [4]:
df.tail()

,Dist Code,Year,State Code,State Name,Dist Name,RICE AREA (1000 ha),RICE PRODUCTION (1000 tons),RICE YIELD (Kg per ha),WHEAT AREA (1000 ha),WHEAT PRODUCTION (1000 tons),...,SUGARCANE YIELD (Kg per ha),COTTON AREA (1000 ha),COTTON PRODUCTION (1000 tons),COTTON YIELD (Kg per ha),FRUITS AREA (1000 ha),VEGETABLES AREA (1000 ha),FRUITS AND VEGETABLES AREA (1000 ha),POTATOES AREA (1000 ha),ONION AREA (1000 ha),FODDER AREA (1000 ha)
16141,917,2013,15,Jharkhand,Singhbhum,267.06,579.70,2170.67,1.53,1.85,...,0.0,0.0,0.0,0.0,0.00,9.02,9.03,0.48,0.08,0.0
16142,917,2014,15,Jharkhand,Singhbhum,256.33,586.63,2288.57,5.36,6.65,...,0.0,0.0,0.0,0.0,0.00,8.63,8.64,0.46,0.04,0.0
16143,917,2015,15,Jharkhand,Singhbhum,263.21,264.71,1005.70,1.99,1.82,...,0.0,0.0,0.0,0.0,0.00,6.84,6.85,0.42,0.01,0.0
16144,917,2016,15,Jharkhand,Singhbhum,224.05,319.01,1423.84,0.38,0.83,...,0.0,0.0,0.0,0.0,0.03,6.40,6.43,0.03,0.01,0.0
16145,917,2017,15,Jharkhand,Singhbhum,386.91,669.97,1731.62,0.00,0.00,...,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.0

<b><span style="color: #5F5F5F; background-color: #F2F4F2; padding: 20px; font-size: 18px; border-left: 8px solid #A9A9A9">📌 Dataset shape </span></b>

In [5]:
df.shape

(16146, 80)

<b><span style="color: #5F5F5F; background-color: #F2F4F2; padding: 20px; font-size: 18px; border-left: 8px solid #A9A9A9">📌 Total information of the dataset </span></b>

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16146 entries, 0 to 16145
Data columns (total 80 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   Dist Code                                    16146 non-null  int64
 1   Year                                         16146 non-null  int64
 2   State Code                                   16146 non-null  int64
 3   State Name                                   16146 non-null  object
 4   Dist Name                                    16146 non-null  object
 5   RICE AREA (1000 ha)                          16146 non-null  float64
 6   RICE PRODUCTION (1000 tons)                  16146 non-null  float64
 7   RICE YIELD (Kg per ha)                       16146 non-null  float64
 8   WHEAT AREA (1000 ha)                         16146 non-null  float64
 9   WHEAT PRODUCTION (1000 tons)                 16146 non-null  float64
 10  WHEAT YIELD (Kg per ha)                      16146 non-null  float64
 11  KHARIF SORGHUM AREA (1000 ha)                16146 non-null  float64
 12  KHARIF SORGHUM PRODUCTION (1000 tons)        16146 non-null  float64
 13  KHARIF SORGHUM YIELD (Kg per ha)             16146 non-null  float64
 14  RABI SORGHUM AREA (1000 ha)                  16146 non-null  float64
 15  RABI SORGHUM PRODUCTION (1000 tons)          16146 non-null  float64
 16  RABI SORGHUM YIELD (Kg per ha)               16146 non-null  float64
 17  SORGHUM AREA (1000 ha)                       16146 non-null  float64
 18  SORGHUM PRODUCTION (1000 tons)               16146 non-null  float64
 19  SORGHUM YIELD (Kg per ha)                    16146 non-null  float64
 20  PEARL MILLET AREA (1000 ha)                  16146 non-null  float64
 21  PEARL MILLET PRODUCTION (1000 tons)          16146 non-null  float64
 22  PEARL MILLET YIELD (Kg per ha)               16146 non-null  float64
 23  MAIZE AREA (1000 ha)                         16146 non-null  float64
 24  MAIZE PRODUCTION (1000 tons)                 16146 non-null  float64
 25  MAIZE YIELD (Kg per ha)                      16146 non-null  float64
 26  FINGER MILLET AREA (1000 ha)                 16146 non-null  float64
 27  FINGER MILLET PRODUCTION (1000 tons)         16146 non-null  float64
 28  FINGER MILLET YIELD (Kg per ha)              16146 non-null  float64
 29  BARLEY AREA (1000 ha)                        16146 non-null  float64
 30  BARLEY PRODUCTION (1000 tons)                16146 non-null  float64
 31  BARLEY YIELD (Kg per ha)                     16146 non-null  float64
 32  CHICKPEA AREA (1000 ha)                      16146 non-null  float64
 33  CHICKPEA PRODUCTION (1000 tons)              16146 non-null  float64
 34  CHICKPEA YIELD (Kg per ha)                   16146 non-null  float64
 35  PIGEONPEA AREA (1000 ha)                     16146 non-null  float64
 36  PIGEONPEA PRODUCTION (1000 tons)             16146 non-null  float64
 37  PIGEONPEA YIELD (Kg per ha)                  16146 non-null  float64
 38  MINOR PULSES AREA (1000 ha)                  16146 non-null  float64
 39  MINOR PULSES PRODUCTION (1000 tons)          16146 non-null  float64
 40  MINOR PULSES YIELD (Kg per ha)               16146 non-null  float64
 41  GROUNDNUT AREA (1000 ha)                     16146 non-null  float64
 42  GROUNDNUT PRODUCTION (1000 tons)             16146 non-null  float64
 43  GROUNDNUT YIELD (Kg per ha)                  16146 non-null  float64
 44  SESAMUM AREA (1000 ha)                       16146 non-null  float64
 45  SESAMUM PRODUCTION (1000 tons)               16146 non-null  float64
 46  SESAMUM YIELD (Kg per ha)                    16146 non-null  float64
 47  RAPESEED AND MUSTARD AREA (1000 ha)          16146 non-null  float64
 48  RAPESEED AND MUSTARD PRODUCTION (1000 tons)  16146 non-null  float64
 49  RAPESEED AND MUSTARD YIELD (Kg per ha)       16146 non-null  float64
 50  SAFFLOWER AREA (1000 ha)                     16146 non-null  float64
 51  SAFFLOWER PRODUCTION (1000 tons)             16146 non-null  float64
 52  SAFFLOWER YIELD (Kg per ha)                  16146 non-null  float64
 53  CASTOR AREA (1000 ha)                        16146 non-null  float64
 54  CASTOR PRODUCTION (1000 tons)                16146 non-null  float64
 55  CASTOR YIELD (Kg per ha)                     16146 non-null  float64
 56  LINSEED AREA (1000 ha)                       16146 non-null  float64
 57  LINSEED PRODUCTION (1000 tons)               16146 non-null  float64
 58  LINSEED YIELD (Kg per ha)                    16146 non-null  float64
 59  SUNFLOWER AREA (1000 ha)                     16146 non-null  float64
 60  SUNFLOWER PRODUCTION (1000 tons)             16146 non-null  float64
 61  SUNFLOWER YIELD (Kg per ha)                  16146 non-null  float64
 62  SOYABEAN AREA (1000 ha)                      16146 non-null  float64
 63  SOYABEAN PRODUCTION (1000 tons)              16146 non-null  float64
 64  SOYABEAN YIELD (Kg per ha)                   16146 non-null  float64
 65  OILSEEDS AREA (1000 ha)                      16146 non-null  float64
 66  OILSEEDS PRODUCTION (1000 tons)              16146 non-null  float64
 67  OILSEEDS YIELD (Kg per ha)                   16146 non-null  float64
 68  SUGARCANE AREA (1000 ha)                     16146 non-null  float64
 69  SUGARCANE PRODUCTION (1000 tons)             16146 non-null  float64
 70  SUGARCANE YIELD (Kg per ha)                  16146 non-null  float64
 71  COTTON AREA (1000 ha)                        16146 non-null  float64
 72  COTTON PRODUCTION (1000 tons)                16146 non-null  float64
 73  COTTON YIELD (Kg per ha)                     16146 non-null  float64
 74  FRUITS AREA (1000 ha)                        16146 non-null  float64
 75  VEGETABLES AREA (1000 ha)                    16146 non-null  float64
 76  FRUITS AND VEGETABLES AREA (1000 ha)         16146 non-null  float64
 77  POTATOES AREA (1000 ha)                      16146 non-null  float64
 78  ONION AREA (1000 ha)                         16146 non-null  float64
 79  FODDER AREA (1000 ha)                        16146 non-null  float64
dtypes: float64(75), int64(3), object(2)
memory usage: 9.9+ MB

<b><span style="color: #5F5F5F; background-color: #F2F4F2; padding: 20px; font-size: 18px; border-left: 8px solid #A9A9A9">📌 Checking null values </span></b>

In [88]:
df.isnull().sum()

Dist Code                               0
Year                                    0
State Code                              0
State Name                              0
Dist Name                               0
                                       ..
VEGETABLES AREA (1000 ha)               0
FRUITS AND VEGETABLES AREA (1000 ha)    0
POTATOES AREA (1000 ha)                 0
ONION AREA (1000 ha)                    0
FODDER AREA (1000 ha)                   0
Length: 80, dtype: int64

<b><span style="color: #5F5F5F; background-color: #F2F4F2; padding: 20px; font-size: 18px; border-left: 8px solid #A9A9A9">📌 Checking duplicates </span></b>

In [8]:
df.duplicated().sum()

0

<b><span style="color: #5F5F5F; background-color: #F2F4F2; padding: 20px; font-size: 18px; border-left: 8px solid #A9A9A9">📌 Extra statistical measures </span></b>

In [9]:
df.describe()

,Dist Code,Year,State Code,RICE AREA (1000 ha),RICE PRODUCTION (1000 tons),RICE YIELD (Kg per ha),WHEAT AREA (1000 ha),WHEAT PRODUCTION (1000 tons),WHEAT YIELD (Kg per ha),KHARIF SORGHUM AREA (1000 ha),...,SUGARCANE YIELD (Kg per ha),COTTON AREA (1000 ha),COTTON PRODUCTION (1000 tons),COTTON YIELD (Kg per ha),FRUITS AREA (1000 ha),VEGETABLES AREA (1000 ha),FRUITS AND VEGETABLES AREA (1000 ha),POTATOES AREA (1000 ha),ONION AREA (1000 ha),FODDER AREA (1000 ha)
count,16146.000000,16146.000000,16146.000000,16146.000000,16146.000000,16146.000000,16146.000000,16146.000000,16146.000000,16146.000000,...,16146.00000,16146.000000,16146.000000,16146.000000,16146.000000,16146.000000,16146.000000,16146.000000,16146.000000,16146.000000
mean,269.769231,1991.496841,9.568562,128.593192,224.889565,1486.924784,77.057946,182.012746,1492.419859,22.632268,...,4500.15306,28.018367,7.229225,124.644823,7.750478,11.086250,18.677877,3.177038,1.194604,21.550328
std,278.309125,15.011185,4.988538,160.078825,326.629828,956.185281,100.394479,348.834254,1081.255367,45.062714,...,3153.97042,74.239648,25.042132,207.681147,13.591135,18.003257,25.881842,8.029509,4.285067,60.062601
min,1.000000,1966.000000,1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,...,-1.00000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000
25%,78.000000,1978.000000,6.000000,10.400000,9.460000,800.000000,1.770000,2.000000,750.000000,0.000000,...,2000.00000,0.000000,0.000000,0.000000,0.310000,1.600000,2.520000,0.000000,0.060000,0.000000
50%,156.000000,1991.000000,10.000000,66.800000,95.840000,1333.210000,36.800000,42.700000,1347.450000,2.050000,...,4502.21000,0.050000,0.000000,0.000000,2.220000,4.740000,8.945000,0.390000,0.280000,1.200000
75%,241.000000,2005.000000,12.000000,191.390000,315.715000,2113.517500,123.000000,215.192500,2131.580000,20.900000,...,6704.60500,10.097500,2.000000,202.270000,8.790000,12.510000,23.570000,3.150000,0.880000,16.762500
max,917.000000,2017.000000,20.000000,1154.230000,3215.010000,5653.830000,879.490000,4305.500000,5541.520000,334.800000,...,22062.30000,800.890000,376.610000,5000.000000,159.540000,200.060000,240.990000,111.610000,131.350000,1162.660000

<b><span style="color: #5F5F5F; background-color: #F2F4F2; padding: 20px; font-size: 18px; border-left: 8px solid #A9A9A9">📌 Showing all the columns </span></b>

In [10]:
df.columns

Index(['Dist Code', 'Year', 'State Code', 'State Name', 'Dist Name',
       'RICE AREA (1000 ha)', 'RICE PRODUCTION (1000 tons)',
       'RICE YIELD (Kg per ha)', 'WHEAT AREA (1000 ha)',
       'WHEAT PRODUCTION (1000 tons)', 'WHEAT YIELD (Kg per ha)',
       'KHARIF SORGHUM AREA (1000 ha)',
       'KHARIF SORGHUM PRODUCTION (1000 tons)',
       'KHARIF SORGHUM YIELD (Kg per ha)', 'RABI SORGHUM AREA (1000 ha)',
       'RABI SORGHUM PRODUCTION (1000 tons)', 'RABI SORGHUM YIELD (Kg per ha)',
       'SORGHUM AREA (1000 ha)', 'SORGHUM PRODUCTION (1000 tons)',
       'SORGHUM YIELD (Kg per ha)', 'PEARL MILLET AREA (1000 ha)',
       'PEARL MILLET PRODUCTION (1000 tons)', 'PEARL MILLET YIELD (Kg per ha)',
       'MAIZE AREA (1000 ha)', 'MAIZE PRODUCTION (1000 tons)',
       'MAIZE YIELD (Kg per ha)', 'FINGER MILLET AREA (1000 ha)',
       'FINGER MILLET PRODUCTION (1000 tons)',
       'FINGER MILLET YIELD (Kg per ha)', 'BARLEY AREA (1000 ha)',
       'BARLEY PRODUCTION (1000 tons)', 'BARLEY YIELD (Kg per ha)',
       'CHICKPEA AREA (1000 ha)', 'CHICKPEA PRODUCTION (1000 tons)',
       'CHICKPEA YIELD (Kg per ha)', 'PIGEONPEA AREA (1000 ha)',
       'PIGEONPEA PRODUCTION (1000 tons)', 'PIGEONPEA YIELD (Kg per ha)',
       'MINOR PULSES AREA (1000 ha)', 'MINOR PULSES PRODUCTION (1000 tons)',
       'MINOR PULSES YIELD (Kg per ha)', 'GROUNDNUT AREA (1000 ha)',
       'GROUNDNUT PRODUCTION (1000 tons)', 'GROUNDNUT YIELD (Kg per ha)',
       'SESAMUM AREA (1000 ha)', 'SESAMUM PRODUCTION (1000 tons)',
       'SESAMUM YIELD (Kg per ha)', 'RAPESEED AND MUSTARD AREA (1000 ha)',
       'RAPESEED AND MUSTARD PRODUCTION (1000 tons)',
       'RAPESEED AND MUSTARD YIELD (Kg per ha)', 'SAFFLOWER AREA (1000 ha)',
       'SAFFLOWER PRODUCTION (1000 tons)', 'SAFFLOWER YIELD (Kg per ha)',
       'CASTOR AREA (1000 ha)', 'CASTOR PRODUCTION (1000 tons)',
       'CASTOR YIELD (Kg per ha)', 'LINSEED AREA (1000 ha)',
       'LINSEED PRODUCTION (1000 tons)', 'LINSEED YIELD (Kg per ha)',
       'SUNFLOWER AREA (1000 ha)', 'SUNFLOWER PRODUCTION (1000 tons)',
       'SUNFLOWER YIELD (Kg per ha)', 'SOYABEAN AREA (1000 ha)',
       'SOYABEAN PRODUCTION (1000 tons)', 'SOYABEAN YIELD (Kg per ha)',
       'OILSEEDS AREA (1000 ha)', 'OILSEEDS PRODUCTION (1000 tons)',
       'OILSEEDS YIELD (Kg per ha)', 'SUGARCANE AREA (1000 ha)',
       'SUGARCANE PRODUCTION (1000 tons)', 'SUGARCANE YIELD (Kg per ha)',
       'COTTON AREA (1000 ha)', 'COTTON PRODUCTION (1000 tons)',
       'COTTON YIELD (Kg per ha)', 'FRUITS AREA (1000 ha)',
       'VEGETABLES AREA (1000 ha)', 'FRUITS AND VEGETABLES AREA (1000 ha)',
       'POTATOES AREA (1000 ha)', 'ONION AREA (1000 ha)',
       'FODDER AREA (1000 ha)'],
      dtype='object')

<div style="background-color: #088F8F; padding: 20px; border-radius: 10px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);">
    <h1 style="text-align: center; font-size: 36px; color: white; text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.3); margin-bottom: 10px;">Data Analysis and Visualization 📊</h1>
    <p style="text-align: center; font-size: 18px; color: white;"></p>
</div>

<div style="background-color: #AAD7D9; #padding: 20px; border-radius: 20px;">
    <p style="font-size: 40px; font-family: 'Verdana'; color: #3A405A; text-align: center;">Rice</p>
</div>

<b><span style="color: #3C0753; background-color:#AAD7D9; padding: 20px; font-size: 18px; border-left: 8px solid #FF9800">i) Rice production</span></b>

In [3]:
rice_state=df.groupby('State Name')['RICE PRODUCTION (1000 tons)'].sum().sort_values(ascending=False).reset_index().head(10)

rice_state

       State Name  RICE PRODUCTION (1000 tons)
0     West Bengal                    544232.26
1   Uttar Pradesh                    445597.62
2          Punjab                    335040.10
3  Andhra Pradesh                    315185.40
4      Tamil Nadu                    291201.51
5          Orissa                    282532.93
6           Bihar                    231759.00
7    Chhattisgarh                    208208.22
8           Assam                    165205.95
9       Telangana                    152911.74

In [4]:
fig=px.bar(rice_state, x='State Name', y='RICE PRODUCTION (1000 tons)',title='Top 10 rice productions by States',
          labels={'State Name':'State Name','Rice Production':'RICE PRODUCTION (1000 tons)'},
           color='RICE PRODUCTION (1000 tons)', color_continuous_scale='Viridis'
          )
fig.update_layout(xaxis_title='State names', yaxis_title='Rice Production')
fig.update_layout(height=600, width=800)
fig.show()

<b><span style="color: #3C0753; background-color:#AAD7D9; padding: 20px; font-size: 18px; border-left: 8px solid #FF9800">ii) Rice Area</span></b>

In [5]:
rice_area=df.groupby('State Name')['RICE AREA (1000 ha)'].sum().sort_values(ascending=False).reset_index().head(10)

rice_area

       State Name  RICE AREA (1000 ha)
0     West Bengal            279491.45
1   Uttar Pradesh            269169.06
2          Orissa            225285.64
3    Chhattisgarh            184036.34
4           Bihar            180424.25
5  Andhra Pradesh            128980.52
6           Assam            121967.69
7      Tamil Nadu            112459.14
8          Punjab             95821.99
9  Madhya Pradesh             82342.64

In [8]:
fig=px.line(rice_area, x='State Name', y='RICE AREA (1000 ha)',title='Top 10 rice production Areas by States',
          labels={'State Name':'State Name','Rice Area':'RICE AREA (1000 ha)'},
           color='RICE AREA (1000 ha)',
            line_shape="linear",
            markers=True
          )
fig.update_layout(xaxis_title='State names', yaxis_title='Rice Production')
fig.update_traces(marker=dict(size=20))
fig.update_layout(height=600, width=800)
fig.show()

<b><span style="color: #3C0753; background-color:#AAD7D9; padding: 20px; font-size: 18px; border-left: 8px solid #FF9800">iii) By year</span></b>

In [116]:
rice_year=df.groupby('Year')['RICE PRODUCTION (1000 tons)'].sum().sort_values(ascending=False).reset_index().head(10)

rice_year

   Year  RICE PRODUCTION (1000 tons)
0  2016                    117614.10
1  2017                    114319.61
2  2014                    112551.62
3  2013                    109552.42
4  2012                    104237.62
5  2011                    102216.27
6  2015                     98820.51
7  2008                     95226.84
8  2010                     94300.23
9  2007                     93002.77

In [117]:
fig = px.pie(rice_year, names='Year', values='RICE PRODUCTION (1000 tons)',
             title='Total Rice Production by 10 years',
             labels={'Year': 'Year', 'RICE PRODUCTION (1000 tons)': 'RICE PRODUCTION (1000 tons)'},
             color='Year', color_discrete_sequence=px.colors.sequential.Viridis,
             hole=0.1
             )
fig.update_layout(height=600,width=800)
fig.show()

<b><span style="color: #3C0753; background-color:#AAD7D9; padding: 20px; font-size: 18px; border-left: 8px solid #FF9800">iv) Rice yield</span></b>

In [114]:
rice_yield=df.groupby('State Name')['RICE YIELD (Kg per ha)'].sum().sort_values(ascending=False).reset_index().head(10)

rice_yield

       State Name  RICE YIELD (Kg per ha)
0   Uttar Pradesh              3767642.74
1       Karnataka              2125721.28
2          Punjab              1773440.44
3      Tamil Nadu              1755871.99
4  Madhya Pradesh              1575672.54
5     Maharashtra              1463057.73
6     West Bengal              1443769.07
7  Andhra Pradesh              1337079.18
8       Telangana              1020098.92
9          Kerala               995867.63

In [120]:
fig = px.bar(rice_yield, x='State Name', y='RICE YIELD (Kg per ha)',
             title='Total Rice yield by 10 states',
             labels={'State Name': 'State Name', 'RICE YIELD ': 'RICE YIELD (Kg per ha)'},
             color='RICE YIELD (Kg per ha)', color_continuous_scale='inferno'
          )

fig.update_layout(xaxis_title='State names', yaxis_title='Rice yield')
fig.update_layout(height=600,width=800)
fig.show()

<div style="background-color: #F037A5; #padding: 20px; border-radius: 20px;">
    <p style="font-size: 40px; font-family: 'Verdana'; color: #3A405A; text-align: center;">Wheat</p>
</div>

<b><span style="color: #3C0753; background-color:#F037A5; padding: 20px; font-size: 18px; border-left: 8px solid F037A5">i) By production</span></b>

In [122]:
wheat_state=df.groupby('State Name')['WHEAT PRODUCTION (1000 tons)'].sum().sort_values(ascending=False).reset_index().head(10)

wheat_state

       State Name  WHEAT PRODUCTION (1000 tons)
0   Uttar Pradesh                     970210.07
1          Punjab                     593848.90
2         Haryana                     348429.60
3  Madhya Pradesh                     338644.25
4       Rajasthan                     265994.99
5           Bihar                     176250.30
6         Gujarat                      85537.63
7     Maharashtra                      54003.95
8     West Bengal                      32703.86
9     Uttarakhand                      25995.57

In [123]:
fig = px.sunburst(wheat_state, path=['State Name'], values='WHEAT PRODUCTION (1000 tons)',
                  title='Total Wheat Production by 10 states',
                  color='WHEAT PRODUCTION (1000 tons)', color_continuous_scale=px.colors.sequential.Inferno,
                
                  )

fig.update_layout(height=600, width=800)
fig.show()

<b><span style="color: #3C0753; background-color:#F037A5; padding: 20px; font-size: 18px; border-left: 8px solid F037A5">ii) By area</span></b>

In [111]:
wheat_area=df.groupby('State Name')['WHEAT AREA (1000 ha)'].sum().sort_values(ascending=False).reset_index().head(10)

wheat_area

         State Name  WHEAT AREA (1000 ha)
0     Uttar Pradesh             418455.35
1    Madhya Pradesh             201914.09
2            Punjab             159102.06
3         Rajasthan             109891.84
4           Haryana              98464.84
5             Bihar              95053.36
6       Maharashtra              48809.70
7           Gujarat              36657.39
8  Himachal Pradesh              17341.53
9       West Bengal              15500.29

In [124]:
fig = px.bar(wheat_area, x='State Name', y='WHEAT AREA (1000 ha)',
             title='Total Wheat Area by 10 states',
             labels={'State Name': 'State Name', 'WHEAT AREA ': 'WHEAT AREA (1000 ha)'},
             color='WHEAT AREA (1000 ha)', color_continuous_scale='sunset'
          )

fig.update_layout(xaxis_title='State names', yaxis_title='Wheat Area')
fig.update_layout(height=600,width=800)
fig.show()

<b><span style="color: #3C0753; background-color:#F037A5; padding: 20px; font-size: 18px; border-left: 8px solid F037A5">iii) By yield</span></b>

In [126]:
wheat_yield=df.groupby('State Name')['WHEAT YIELD (Kg per ha)'].sum().sort_values(ascending=False).reset_index().head(10)

wheat_yield

       State Name  WHEAT YIELD (Kg per ha)
0   Uttar Pradesh               5208756.43
1  Madhya Pradesh               2930771.89
2       Rajasthan               2722217.00
3          Punjab               2007153.14
4         Gujarat               1991362.26
5     West Bengal               1438980.99
6     Maharashtra               1288086.69
7         Haryana               1161151.95
8          Orissa               1054791.18
9           Bihar                992099.68

In [130]:
fig = px.line(wheat_yield, x='State Name', y='WHEAT YIELD (Kg per ha)',
             title='Total Wheat yield by 10 states',
             labels={'State Name': 'State Name', 'WHEAT yield ': 'WHEAT YIELD (Kg per ha)'},
             color='WHEAT YIELD (Kg per ha)',
             line_shape="linear",
            markers=True,
            
             )

fig.update_layout(xaxis_title='State names', yaxis_title='Wheat Area')
fig.update_layout(template='gridon')
fig.update_traces(marker=dict(size=30))
fig.update_layout(height=600,width=800)
fig.show()

<div style="background-color: #F6B17A; #padding: 20px; border-radius: 20px;">
    <p style="font-size: 40px; font-family: 'Verdana'; color: #3A405A; text-align: center;">Barley</p>
</div>

<b><span style="color: #3C0753; background-color:#F6B17A; padding: 20px; font-size: 18px; border-left: 8px solid F037A5">i) By area</span></b>

In [107]:
barley_area=df.groupby('State Name')['BARLEY AREA (1000 ha)'].sum().sort_values(ascending=False).reset_index().head(10)

barley_area

         State Name  BARLEY AREA (1000 ha)
0     Uttar Pradesh               29135.26
1         Rajasthan               17222.25
2    Madhya Pradesh                6046.81
3             Bihar                4038.64
4           Haryana                3921.86
5            Punjab                2338.98
6  Himachal Pradesh                1452.34
7       Uttarakhand                1150.91
8       West Bengal                1051.47
9         Jharkhand                 518.80

In [126]:
fig = px.bar(barley_area, x='State Name', y='BARLEY AREA (1000 ha)',
             title='Total Barley Area by 10 states',
             labels={'State Name': 'State Name', 'BARLEY AREA ': 'BARLEY AREA (1000 ha)'},
             color='BARLEY AREA (1000 ha)', color_continuous_scale='icefire'
          )

fig.update_layout(xaxis_title='State names', yaxis_title='Barley Area')
fig.update_layout(template='gridon')
fig.update_layout(height=600,width=800)
fig.show()

<b><span style="color: #3C0753; background-color:#F6B17A; padding: 20px; font-size: 18px; border-left: 8px solid F037A5">ii) By production</span></b>

In [122]:
barley_pro=df.groupby('State Name')['BARLEY PRODUCTION (1000 tons)'].sum().sort_values(ascending=False).reset_index().head(10)

barley_pro

         State Name  BARLEY PRODUCTION (1000 tons)
0     Uttar Pradesh                       39496.06
1         Rajasthan                       29944.48
2    Madhya Pradesh                        6958.06
3           Haryana                        6712.70
4            Punjab                        4450.00
5             Bihar                        2832.41
6  Himachal Pradesh                        1770.83
7       Uttarakhand                        1278.12
8       West Bengal                         848.13
9         Jharkhand                         283.18

In [124]:
fig = px.scatter(
    barley_pro,
    x="State Name",
    y="BARLEY PRODUCTION (1000 tons)",
    size="BARLEY PRODUCTION (1000 tons)",  
    color="BARLEY PRODUCTION (1000 tons)",  
    title="Barley Production by 10 States",
    color_continuous_scale='Magma',
    size_max=40)

fig.update_layout(
    height=600,
    width=800,
    xaxis_title="State Name",
    yaxis_title="Barley Production (1000 tons)",
    showlegend=True,  # Show legend if using color
)
fig.update_layout(template='gridon')
fig.show()

<b><span style="color: #3C0753; background-color:#F6B17A; padding: 20px; font-size: 18px; border-left: 8px solid F037A5">iii) By yield</span></b>

In [104]:
barley_yield=df.groupby('State Name')['BARLEY YIELD (Kg per ha)'].sum().sort_values(ascending=False).reset_index().head(10)

barley_yield

         State Name  BARLEY YIELD (Kg per ha)
0     Uttar Pradesh                3890223.09
1         Rajasthan                2418710.93
2    Madhya Pradesh                1810826.41
3            Punjab                 818879.75
4           Haryana                 636211.21
5  Himachal Pradesh                 614128.75
6             Bihar                 522411.69
7       Uttarakhand                 399844.99
8       West Bengal                 375127.66
9      Chhattisgarh                 148418.21

In [130]:
fig = px.pie(barley_yield, names='State Name', values='BARLEY YIELD (Kg per ha)',
             title='Total Barley yield by 10 states',
             labels={'State Name': 'State Name', 'BARLEY YIELD (Kg per ha) ': 'BARLEY YIELD (Kg per ha)'},
             color_discrete_sequence=px.colors.sequential.Turbo
             )

fig.update_layout(xaxis_title='State names', yaxis_title='Barley yield')
fig.update_layout(height=600,width=800)
fig.update_layout(template='gridon')
fig.show()

<div style="background-color: #EA9085; #padding: 20px; border-radius: 20px;">
    <p style="font-size: 40px; font-family: 'Verdana'; color: #3A405A; text-align: center;">Sunflower</p>
</div>

<b><span style="color: #3C0753; background-color:#EA9085; padding: 20px; font-size: 18px; border-left: 8px solid F037A5">i) By area</span></b>

In [95]:
sunflower_area=df.groupby('State Name')['SUNFLOWER AREA (1000 ha)'].sum().sort_values(ascending=False).reset_index().head(10)

sunflower_area

       State Name  SUNFLOWER AREA (1000 ha)
0       Karnataka                  26098.42
1     Maharashtra                  10941.68
2  Andhra Pradesh                   6561.10
3       Telangana                   1820.81
4      Tamil Nadu                    864.03
5          Punjab                    681.29
6   Uttar Pradesh                    434.44
7           Bihar                    358.72
8          Orissa                    330.85
9  Madhya Pradesh                    158.64

In [131]:
fig = px.bar(sunflower_area, x='State Name', y='SUNFLOWER AREA (1000 ha)',
             title='Total Sunflower Area by 10 states',
             labels={'State Name': 'State Name', 'SUNFLOWER AREA (1000 ha) ': 'SUNFLOWER AREA (1000 ha)'},
             color='SUNFLOWER AREA (1000 ha)', color_continuous_scale='viridis'
          )

fig.update_layout(xaxis_title='State names', yaxis_title='Sunflower Area')

fig.update_layout(template='plotly_white')
fig.update_layout(height=600,width=800)
fig.show()

<b><span style="color: #3C0753; background-color:#EA9085; padding: 20px; font-size: 18px; border-left: 8px solid F037A5">ii) By production</span></b>

In [117]:
sun_pro=df.groupby('State Name')['SUNFLOWER PRODUCTION (1000 tons)'].sum().sort_values(ascending=False).reset_index().head(10)

sun_pro

       State Name  SUNFLOWER PRODUCTION (1000 tons)
0       Karnataka                          10785.87
1     Maharashtra                           5599.46
2  Andhra Pradesh                           4447.78
3       Telangana                           1401.06
4          Punjab                           1081.86
5      Tamil Nadu                            762.38
6   Uttar Pradesh                            552.66
7           Bihar                            453.34
8          Orissa                            322.85
9     West Bengal                            131.99

In [119]:
fig = px.scatter(
    sun_pro,
    x="State Name",
    y="SUNFLOWER PRODUCTION (1000 tons)",
    size="SUNFLOWER PRODUCTION (1000 tons)",  
    color="SUNFLOWER PRODUCTION (1000 tons)",  
    title="Sunflower Production by 10 States",
    color_continuous_scale='Inferno',
    size_max=70)

fig.update_layout(
    height=600,
    width=800,
    xaxis_title="State Name",
    yaxis_title="SUNFLOWER PRODUCTION (1000 tons)",
    showlegend=True,  
)
fig.update_layout(template='plotly_white')
fig.show()

<b><span style="color: #3C0753; background-color:#EA9085; padding: 20px; font-size: 18px; border-left: 8px solid F037A5">iii) By yield</span></b>

In [102]:
sun_yield=df.groupby('State Name')['SUNFLOWER YIELD (Kg per ha)'].sum().sort_values(ascending=False).reset_index().head(10)

sun_yield

       State Name  SUNFLOWER YIELD (Kg per ha)
0   Uttar Pradesh                   1402650.58
1     Maharashtra                    399659.29
2      Tamil Nadu                    358404.28
3       Karnataka                    352939.48
4           Bihar                    303007.22
5          Punjab                    300104.27
6          Orissa                    295449.24
7       Telangana                    267627.41
8  Andhra Pradesh                    261316.67
9     West Bengal                    221732.19

In [133]:
fig = px.pie(sun_yield, names='State Name', values='SUNFLOWER YIELD (Kg per ha)',
                  title='Total Sunflower yield by 10 states',
                  color='State Name',color_discrete_sequence=px.colors.sequential.Burgyl 
                
                  )

fig.update_layout(height=600, width=800)
fig.update_layout(template='plotly_white')
fig.show()

<div style="background-color: #E0AED0; #padding: 20px; border-radius: 20px;">
    <p style="font-size: 40px; font-family: 'Verdana'; color: #3A405A; text-align: center;">Soyabean</p>
</div>

<b><span style="color: #3C0753; background-color:#E0AED0; padding: 20px; font-size: 18px; border-left: 8px solid F037A5">i) By area</span></b>

In [91]:
soya_area=df.groupby('State Name')['SOYABEAN AREA (1000 ha)'].sum().sort_values(ascending=False).reset_index().head(10)

soya_area

       State Name  SOYABEAN AREA (1000 ha)
0  Madhya Pradesh                137165.32
1     Maharashtra                 54582.37
2       Rajasthan                 19052.48
3       Karnataka                  3500.48
4       Telangana                  2149.76
5    Chhattisgarh                  1565.97
6     Uttarakhand                   963.98
7   Uttar Pradesh                   819.27
8         Gujarat                   746.19
9      Tamil Nadu                    94.21

In [134]:
fig = px.bar(soya_area, x='State Name', y='SOYABEAN AREA (1000 ha)',
             title='Total Soyabean Area by 10 states',
             labels={'State Name': 'State Name', 'SOYABEAN AREA (1000 ha)) ': 'SOYABEAN AREA (1000 ha)'},
             color='SOYABEAN AREA (1000 ha)', color_continuous_scale='purpor'
          )

fig.update_layout(xaxis_title='State names', yaxis_title='Soyabean Area')

fig.update_layout(template='ggplot2')
fig.update_layout(height=600,width=800)
fig.show()

<b><span style="color: #3C0753; background-color:#E0AED0; padding: 20px; font-size: 18px; border-left: 8px solid F037A5">ii) By production</span></b>

In [87]:
soya_pro=df.groupby('State Name')['SOYABEAN PRODUCTION (1000 tons)'].sum().sort_values(ascending=False).reset_index().head(10)

soya_pro

       State Name  SOYABEAN PRODUCTION (1000 tons)
0  Madhya Pradesh                        136006.52
1     Maharashtra                         58643.93
2       Rajasthan                         21174.99
3       Telangana                          3022.13
4       Karnataka                          2873.98
5    Chhattisgarh                          1287.53
6     Uttarakhand                           975.61
7         Gujarat                           602.63
8   Uttar Pradesh                           544.46
9  Andhra Pradesh                            24.28

In [135]:
fig = px.line(soya_pro, x='State Name', y='SOYABEAN PRODUCTION (1000 tons)',
             title='Total Soyabean yield by 10 states',
             labels={'State Name': 'State Name', 'SOYABEAN PRODUCTION (1000 tons) ': 'SOYABEAN PRODUCTION (1000 tons)'},
             color='SOYABEAN PRODUCTION (1000 tons)',
             line_shape="linear",
            markers=True
             )

fig.update_layout(xaxis_title='State names', yaxis_title='Soya Area')
fig.update_layout(template='ggplot2')
fig.update_layout(height=600,width=800)
fig.update_traces(marker=dict(size=20))
fig.show()

<b><span style="color: #3C0753; background-color:#E0AED0; padding: 20px; font-size: 18px; border-left: 8px solid F037A5">iii) By yield</span></b>

In [85]:
soya_yield=df.groupby('State Name')['SOYABEAN YIELD (Kg per ha)'].sum().sort_values(ascending=False).reset_index().head(10)

soya_yield

         State Name  SOYABEAN YIELD (Kg per ha)
0    Madhya Pradesh                  1161169.25
1       Maharashtra                   770938.60
2         Rajasthan                   404598.94
3     Uttar Pradesh                   341798.02
4       Uttarakhand                   254553.66
5         Karnataka                   201773.29
6  Himachal Pradesh                   188267.26
7      Chhattisgarh                   162243.17
8         Telangana                   119230.77
9           Gujarat                   112370.42

In [136]:
fig = px.pie(soya_yield, names='State Name', values='SOYABEAN YIELD (Kg per ha)',
             title='Total Soyabean yield by 10 states',
             labels={'Year': 'Year', 'SOYABEAN YIELD (Kg per ha)': 'SOYABEAN YIELD (Kg per ha)'},
             color='SOYABEAN YIELD (Kg per ha)', color_discrete_sequence=px.colors.sequential.Oranges ,
             hole=0.05
             )

fig.update_layout(template='ggplot2')
fig.update_layout(height=600,width=800)
fig.show()

<div style="background-color: #BED754; #padding: 20px; border-radius: 20px;">
    <p style="font-size: 40px; font-family: 'Verdana'; color: #3A405A; text-align: center;">Oilseeds</p>
</div>

<b><span style="color: #3C0753; background-color:#BED754; padding: 20px; font-size: 18px; border-left: 8px solid F037A5">i) By area</span></b>

In [83]:
oil_area=df.groupby('State Name')['OILSEEDS AREA (1000 ha)'].sum().sort_values(ascending=False).reset_index().head(10)

oil_area

       State Name  OILSEEDS AREA (1000 ha)
0  Madhya Pradesh                189945.92
1       Rajasthan                142433.47
2     Maharashtra                134069.16
3         Gujarat                130724.71
4       Karnataka                 92527.23
5  Andhra Pradesh                 87223.49
6      Tamil Nadu                 56225.64
7   Uttar Pradesh                 43047.07
8          Orissa                 39682.05
9       Telangana                 35293.43

In [137]:
fig = px.bar(oil_area, x='State Name', y='OILSEEDS AREA (1000 ha)',
             title='Total Oilseeds Area by 10 states',
             labels={'State Name': 'State Name', 'OILSEEDS AREA (1000 ha) ': 'OILSEEDS AREA (1000 ha)'},
             color='OILSEEDS AREA (1000 ha)', color_continuous_scale='blackbody'
          )

fig.update_layout(xaxis_title='State names', yaxis_title='Soyabean Area')

fig.update_layout(template='ggplot2')
fig.update_layout(height=600,width=800)
fig.show()

<b><span style="color: #3C0753; background-color:#BED754; padding: 20px; font-size: 18px; border-left: 8px solid F037A5">ii) By production</span></b>

In [111]:
oil_pro=df.groupby('State Name')['OILSEEDS PRODUCTION (1000 tons)'].sum().sort_values(ascending=False).reset_index().head(10)

oil_pro

       State Name  OILSEEDS PRODUCTION (1000 tons)
0  Madhya Pradesh                        153594.79
1         Gujarat                        126224.01
2       Rajasthan                        122726.86
3     Maharashtra                         95567.91
4  Andhra Pradesh                         76888.09
5      Tamil Nadu                         55275.03
6       Karnataka                         52599.04
7          Orissa                         28453.77
8   Uttar Pradesh                         24015.98
9         Haryana                         24006.60

In [115]:
fig = px.scatter(
    oil_pro,
    x="State Name",
    y="OILSEEDS PRODUCTION (1000 tons)",
    size="OILSEEDS PRODUCTION (1000 tons)",  
    color="OILSEEDS PRODUCTION (1000 tons)",  
    title="Oilseed Production by 10 States",
    color_continuous_scale='Sunset',
    size_max=40)

fig.update_layout(
    height=600,
    width=800,
    xaxis_title="State Name",
    yaxis_title="Oilseed production (1000 tons)",
    showlegend=True,  
)
fig.update_layout(template='ggplot2')
fig.show()

<b><span style="color: #3C0753; background-color:#BED754; padding: 20px; font-size: 18px; border-left: 8px solid F037A5">iii) By yield</span></b>

In [81]:
oil_yield=df.groupby('State Name')['OILSEEDS YIELD (Kg per ha)'].sum().sort_values(ascending=False).reset_index().head(10)

oil_yield

       State Name  OILSEEDS YIELD (Kg per ha)
0   Uttar Pradesh                  1130945.89
1  Madhya Pradesh                  1067368.24
2       Rajasthan                   835732.81
3     Maharashtra                   829019.39
4         Gujarat                   815220.14
5  Andhra Pradesh                   724896.26
6       Karnataka                   655625.53
7      Tamil Nadu                   503284.68
8          Punjab                   491317.60
9          Orissa                   478458.08

In [141]:
fig = px.pie(oil_yield, names='State Name', values='OILSEEDS YIELD (Kg per ha)',
             title='Total Soyabean yield by 10 states',
             labels={'State Name': 'State Name', 'OILSEEDS YIELD (Kg per ha)': 'OILSEEDS YIELD (Kg per ha)'},
             color='State Name', color_discrete_sequence=px.colors.sequential.Blackbody ,
             hole=0.1
             )

fig.update_layout(template='ggplot2')
fig.update_layout(height=600,width=800)
fig.show()

<div style="background-color: #CD8D7B; #padding: 20px; border-radius: 20px;">
    <p style="font-size: 40px; font-family: 'Verdana'; color: #3A405A; text-align: center;">Cotton</p>
</div>

<b><span style="color: #3C0753; background-color:#CD8D7B; padding: 20px; font-size: 18px; border-left: 8px solid F037A5">i) By area</span></b>

In [9]:
cotton_area=df.groupby('State Name')['COTTON AREA (1000 ha)'].sum().sort_values(ascending=False).reset_index().head(10)

cotton_area

       State Name  COTTON AREA (1000 ha)
0     Maharashtra              154319.82
1         Gujarat               94325.68
2       Karnataka               37689.74
3  Madhya Pradesh               30653.05
4       Telangana               29639.37
5          Punjab               28579.70
6         Haryana               23062.49
7       Rajasthan               21359.72
8  Andhra Pradesh               18274.69
9      Tamil Nadu               11232.87

In [79]:
fig = px.bar(cotton_area, x='State Name', y='COTTON AREA (1000 ha)',
             title='Total Cotton Area by Top 10 states',
             labels={'State Name': 'State Name', 'COTTON AREA (1000 ha) ': 'COTTON AREA (1000 ha)'},
             color='COTTON AREA (1000 ha)', color_continuous_scale='inferno'
          )

fig.update_layout(xaxis_title='State names', yaxis_title='Cotton Area')

fig.update_layout(template='simple_white')
fig.update_layout(height=600,width=800)
fig.show()

<b><span style="color: #3C0753; background-color:#CD8D7B; padding: 20px; font-size: 18px; border-left: 8px solid F037A5">ii) By production</span></b>

In [109]:
cot_pro=df.groupby('State Name')['COTTON PRODUCTION (1000 tons)'].sum().sort_values(ascending=False).reset_index().head(10)
cot_pro

       State Name  COTTON PRODUCTION (1000 tons)
0         Gujarat                       31359.57
1     Maharashtra                       25217.30
2          Punjab                       12960.99
3         Haryana                        9851.23
4       Telangana                        9410.65
5       Karnataka                        6903.80
6  Andhra Pradesh                        6444.95
7       Rajasthan                        5582.96
8  Madhya Pradesh                        4382.09
9      Tamil Nadu                        3007.77

In [110]:
fig = px.scatter(
    cot_pro,
    x="State Name",
    y="COTTON PRODUCTION (1000 tons)",
    size="COTTON PRODUCTION (1000 tons)",  
    color="COTTON PRODUCTION (1000 tons)",  
    title="Cotton Production by top 10 States",
    color_continuous_scale='Blackbody',
    size_max=40)

fig.update_layout(
    height=600,
    width=800,
    xaxis_title="State Name",
    yaxis_title="Cotton production (1000 tons)",
    showlegend=True,  
)
fig.update_layout(template='simple_white')
fig.show()

<b><span style="color: #3C0753; background-color:#CD8D7B; padding: 20px; font-size: 18px; border-left: 8px solid F037A5">iii) By yield</span></b>

In [28]:
cotton_yield=df.groupby('State Name')['COTTON YIELD (Kg per ha)'].sum().sort_values(ascending=False).reset_index().head(10)

cotton_yield

       State Name  COTTON YIELD (Kg per ha)
0         Gujarat                 273662.77
1       Rajasthan                 254017.67
2     Maharashtra                 199681.68
3      Tamil Nadu                 185599.95
4       Karnataka                 175801.13
5          Punjab                 145983.73
6  Andhra Pradesh                 141582.83
7          Orissa                 126062.67
8       Telangana                 102438.32
9         Haryana                 102400.01

In [31]:
fig = px.sunburst(cotton_yield, path=['State Name'], values='COTTON YIELD (Kg per ha)',
                  title='Total Cotton Yield by top 10 states',
                  color='COTTON YIELD (Kg per ha)', color_continuous_scale=px.colors.sequential.Blackbody,
                
                  )

fig.update_layout(height=600, width=800)
fig.show()

<div style="background-color: #A1EEBD; #padding: 20px; border-radius: 20px;">
    <p style="font-size: 40px; font-family: 'Verdana'; color: #3A405A; text-align: center;">Fruits</p>
</div>

<b><span style="color: #3C0753; background-color:#A1EEBD; padding: 20px; font-size: 18px; border-left: 8px solid F037A5">i) By area</span></b>

In [32]:
fruit_area=df.groupby('State Name')['FRUITS AREA (1000 ha)'].sum().sort_values(ascending=False).reset_index().head(10)

fruit_area

       State Name  FRUITS AREA (1000 ha)
0  Andhra Pradesh               19921.48
1          Kerala               17260.41
2      Tamil Nadu               12621.38
3          Orissa               12050.33
4   Uttar Pradesh               10952.97
5     Maharashtra               10248.41
6       Karnataka                9544.18
7         Gujarat                5665.46
8           Bihar                5468.52
9     West Bengal                4815.92

In [78]:
fig = px.bar(fruit_area, x='State Name', y='FRUITS AREA (1000 ha)',
             title='Total Fruits Area by Top 10 states',
             labels={'State Name': 'State Name', 'FRUITS AREA (1000 ha) ': 'FRUITS AREA (1000 ha)'},
             color='FRUITS AREA (1000 ha)', color_continuous_scale='rainbow'
          )

fig.update_layout(xaxis_title='State names', yaxis_title='Fruit Area')

fig.update_layout(template='plotly_dark')
fig.update_layout(height=600,width=800)
fig.show()

<div style="background-color: #A1EEBD; #padding: 20px; border-radius: 20px;">
    <p style="font-size: 40px; font-family: 'Verdana'; color: #3A405A; text-align: center;">Vegetables</p>
</div>

<b><span style="color: #3C0753; background-color:#A1EEBD; padding: 20px; font-size: 18px; border-left: 8px solid F037A5">i) By area</span></b>

In [40]:
vege_area=df.groupby('State Name')['VEGETABLES AREA (1000 ha)'].sum().sort_values(ascending=False).reset_index().head(10)

vege_area

       State Name  VEGETABLES AREA (1000 ha)
0          Orissa                   30205.39
1     West Bengal                   27656.60
2   Uttar Pradesh                   25228.66
3           Bihar                   12105.66
4          Kerala                   11020.88
5       Karnataka                    9472.33
6      Tamil Nadu                    8108.47
7           Assam                    7868.47
8     Maharashtra                    7599.86
9  Madhya Pradesh                    7148.39

In [53]:
fig = px.pie(vege_area, names='State Name', values='VEGETABLES AREA (1000 ha)',
                  title='Total Vegetable Area by top 10 states',
                  color='VEGETABLES AREA (1000 ha)', color_discrete_sequence=px.colors.sequential.Agsunset
                
                  )

fig.update_layout(height=600, width=800)
fig.update_layout(template='plotly_dark')
fig.show()

<div style="background-color: #A1EEBD; #padding: 20px; border-radius: 20px;">
    <p style="font-size: 40px; font-family: 'Verdana'; color: #3A405A; text-align: center;">Fruits and Vegetables</p>
</div>

<b><span style="color: #3C0753; background-color:#A1EEBD; padding: 20px; font-size: 18px; border-left: 8px solid F037A5">i) By area</span></b>

In [50]:
f_v=df.groupby('State Name')['FRUITS AND VEGETABLES AREA (1000 ha)'].sum().sort_values(ascending=False).reset_index().head(10)

f_v

       State Name  FRUITS AND VEGETABLES AREA (1000 ha)
0          Orissa                              40310.93
1   Uttar Pradesh                              36272.57
2     West Bengal                              32505.49
3          Kerala                              28280.89
4  Andhra Pradesh                              25508.58
5      Tamil Nadu                              20729.34
6       Karnataka                              19015.80
7     Maharashtra                              17848.30
8           Bihar                              17573.54
9         Gujarat                              11494.93

In [77]:
fig = px.line(f_v, x='State Name', y='FRUITS AND VEGETABLES AREA (1000 ha)',
             title='Total Fruits and Vegetable areas by Top 10 states',
             labels={'State Name': 'State Name', 'FRUITS AND VEGETABLES AREA (1000 ha) ': 'FRUITS AND VEGETABLES AREA (1000 ha)'},
             color='FRUITS AND VEGETABLES AREA (1000 ha)',
             line_shape="linear",
            markers=True
             )

fig.update_layout(xaxis_title='State names', yaxis_title='Fruits and Vegetables Area')
fig.update_layout(template='plotly_dark')
fig.update_layout(height=600,width=800)
fig.update_traces(marker=dict(size=16))
fig.show()

<div style="background-color: #F6F7C4; #padding: 20px; border-radius: 20px;">
    <p style="font-size: 40px; font-family: 'Verdana'; color: #3A405A; text-align: center;">Potatoes</p>
</div>

<b><span style="color: #3C0753; background-color:#F6F7C4; padding: 20px; font-size: 18px; border-left: 8px solid F037A5">i) By area</span></b>

In [55]:
pota_area=df.groupby('State Name')['POTATOES AREA (1000 ha)'].sum().sort_values(ascending=False).reset_index().head(10)

pota_area

         State Name  POTATOES AREA (1000 ha)
0     Uttar Pradesh                 18358.69
1       West Bengal                 12191.16
2             Bihar                  5227.58
3             Assam                  3114.10
4            Punjab                  1982.38
5    Madhya Pradesh                  1932.88
6           Gujarat                  1637.61
7         Karnataka                  1457.87
8         Jharkhand                  1388.08
9  Himachal Pradesh                   697.72

In [76]:
fig = px.bar(pota_area, x='State Name', y='POTATOES AREA (1000 ha)',
             title='Total Potatoes Area by Top 10 states',
             labels={'State Name': 'State Name', 'POTATOES AREA (1000 ha) ': 'POTATOES AREA (1000 ha)'},
             color='POTATOES AREA (1000 ha)', color_continuous_scale='haline'
          )

fig.update_layout(xaxis_title='State names', yaxis_title='Potatoes Area')

fig.update_layout(template='plotly_white')
fig.update_layout(height=600,width=800)
fig.show()

<div style="background-color: #F6F7C4; #padding: 20px; border-radius: 20px;">
    <p style="font-size: 40px; font-family: 'Verdana'; color: #3A405A; text-align: center;">Onions</p>
</div>

<b><span style="color: #3C0753; background-color:#F6F7C4; padding: 20px; font-size: 18px; border-left: 8px solid F037A5">i) By area</span></b>

In [62]:
oni_area=df.groupby('State Name')['ONION AREA (1000 ha)'].sum().sort_values(ascending=False).reset_index().head(10)

oni_area

       State Name  ONION AREA (1000 ha)
0       Karnataka               4196.42
1     Maharashtra               3895.57
2          Orissa               1784.09
3         Gujarat               1386.00
4  Madhya Pradesh               1329.12
5       Rajasthan               1266.12
6      Tamil Nadu               1211.67
7   Uttar Pradesh               1012.88
8  Andhra Pradesh                883.17
9           Bihar                547.11

In [75]:
fig = px.pie(oni_area, names='State Name', values='ONION AREA (1000 ha)',
             title='Total Onions Area by top 10 states',
             labels={'State Name': 'State Name', 'ONION AREA (1000 ha)': 'ONION AREA (1000 ha)'},
             color='ONION AREA (1000 ha)', color_discrete_sequence=px.colors.sequential.Magenta ,
             )

fig.update_layout(template='plotly_white')
fig.update_layout(height=600,width=800)
fig.show()

<div style="background-color: #F6F7C4; #padding: 20px; border-radius: 20px;">
    <p style="font-size: 40px; font-family: 'Verdana'; color: #3A405A; text-align: center;">Fodder</p>
</div>

Fodder includes hay, straw, silage, compressed and pelleted feeds, oils and mixed rations, and sprouted grains and legumes (such as bean sprouts, fresh malt, or spent malt). Most animal feed is from plants, but some manufacturers add ingredients to processed feeds that are of animal origin.

<b><span style="color: #3C0753; background-color:#F6F7C4; padding: 20px; font-size: 18px; border-left: 8px solid F037A5">i) By area</span></b>

In [107]:
fodd_area=df.groupby('State Name')['FODDER AREA (1000 ha)'].sum().sort_values(ascending=False).reset_index().head(10)

fodd_area

       State Name  FODDER AREA (1000 ha)
0       Rajasthan              135865.64
1         Gujarat               42778.35
2   Uttar Pradesh               35534.92
3  Madhya Pradesh               32454.03
4     Maharashtra               29725.43
5          Punjab               29585.49
6         Haryana               23854.64
7      Tamil Nadu                6594.76
8  Andhra Pradesh                5951.31
9       Karnataka                3588.23

In [108]:
fig = px.scatter(
    fodd_area,
    x="State Name",
    y="FODDER AREA (1000 ha)",
    size="FODDER AREA (1000 ha)",  
    color="FODDER AREA (1000 ha)",  
    title="Fodder Area by top 10 States",
    size_max=50,
color_continuous_scale='Tealgrn')

fig.update_layout(
    height=600,
    width=800,
    xaxis_title="State Name",
    yaxis_title="Fodder areas",
    showlegend=True,  
)
fig.update_layout(template='gridon')
fig.show()

<div style="background-color: #A1EEBD; #padding: 20px; border-radius: 20px;">
    <p style="font-size: 40px; font-family: 'Verdana'; color: #3A405A; text-align: center;">Kharif Sorghum</p>
</div>

<b><span style="color: #3C0753; background-color:#A1EEBD; padding: 20px; font-size: 18px; border-left: 8px solid F037A5">i) By area</span></b>

In [142]:
kh_area=df.groupby('State Name')['KHARIF SORGHUM AREA (1000 ha)'].sum().sort_values(ascending=False).reset_index().head(10)

kh_area

       State Name  KHARIF SORGHUM AREA (1000 ha)
0     Maharashtra                      110830.43
1  Madhya Pradesh                       68644.32
2       Rajasthan                       40726.33
3       Karnataka                       31799.10
4         Gujarat                       25818.13
5   Uttar Pradesh                       24392.94
6       Telangana                       23201.61
7      Tamil Nadu                       21597.19
8  Andhra Pradesh                        9932.71
9         Haryana                        6589.84

In [164]:
fig = px.bar(kh_area, x='State Name', y='KHARIF SORGHUM AREA (1000 ha)',
             title='Total Kharif Sorghum Area by Top 10 states',
             labels={'State Name': 'State Name', 'KHARIF SORGHUM AREA (1000 ha) ': 'KHARIF SORGHUM AREA (1000 ha)'},
             color='KHARIF SORGHUM AREA (1000 ha)'
          )

fig.update_layout(xaxis_title='State names', yaxis_title='Kharif Sorghum  Area')

fig.update_layout(template='seaborn')
fig.update_layout(height=600,width=800)
fig.show()

<b><span style="color: #3C0753; background-color:#A1EEBD; padding: 20px; font-size: 18px; border-left: 8px solid F037A5">ii) By production</span></b>

In [152]:
kh_pro=df.groupby('State Name')['KHARIF SORGHUM PRODUCTION (1000 tons)'].sum().sort_values(ascending=False).reset_index().head(10)

kh_pro

       State Name  KHARIF SORGHUM PRODUCTION (1000 tons)
0     Maharashtra                              116655.48
1  Madhya Pradesh                               56642.83
2       Karnataka                               35279.76
3   Uttar Pradesh                               18346.30
4      Tamil Nadu                               18108.40
5       Rajasthan                               16850.58
6       Telangana                               13837.10
7         Gujarat                               11373.12
8  Andhra Pradesh                                6195.47
9         Haryana                                1726.00

In [166]:
fig = px.pie(kh_pro, names='State Name', values='KHARIF SORGHUM PRODUCTION (1000 tons)',
             title='Total Kharif Sorghum production by top 10 states',
             labels={'State Name': 'State Name', 'KHARIF SORGHUM PRODUCTION (1000 tons)': 'KHARIF SORGHUM PRODUCTION (1000 tons)'},
             color='KHARIF SORGHUM PRODUCTION (1000 tons)', 
            hole=0.1
            )

fig.update_layout(template='plotly_white')
fig.update_layout(template='seaborn')
fig.update_layout(height=600,width=800)
fig.show()

<b><span style="color: #3C0753; background-color:#A1EEBD; padding: 20px; font-size: 18px; border-left: 8px solid F037A5">iii) By yield</span></b>

In [44]:
kh_y=df.groupby('State Name')['KHARIF SORGHUM YIELD (Kg per ha)'].sum().sort_values(ascending=False).reset_index().head(10)

kh_y

       State Name  KHARIF SORGHUM YIELD (Kg per ha)
0  Madhya Pradesh                        1866540.41
1   Uttar Pradesh                        1778392.95
2     Maharashtra                        1209794.67
3       Karnataka                        1000039.66
4         Gujarat                         581578.97
5       Rajasthan                         574275.40
6      Tamil Nadu                         516923.88
7  Andhra Pradesh                         474138.89
8          Orissa                         401502.93
9       Telangana                         320260.60

In [46]:
fig = px.scatter(
    kh_y,
    x="State Name",
    y="KHARIF SORGHUM YIELD (Kg per ha)",
    size="KHARIF SORGHUM YIELD (Kg per ha)",  
    color="KHARIF SORGHUM YIELD (Kg per ha)",  
    title="KHARIF SORGHUM YIELD (Kg per ha)",
    size_max=50,
color_continuous_scale='Inferno')

fig.update_layout(
    height=600,
    width=800,
    xaxis_title="State Name",
    yaxis_title="Kharif Sorghum yield",
    showlegend=True,  
)
fig.update_layout(template='seaborn')
fig.show()

<div style="background-color: #DF826C; #padding: 20px; border-radius: 20px;">
    <p style="font-size: 40px; font-family: 'Verdana'; color: #3A405A; text-align: center;">Rabi Sorghum</p>
</div>

<b><span style="color: #3C0753; background-color:#DF826C; padding: 20px; font-size: 18px; border-left: 8px solid F037A5">i) By area</span></b>

In [3]:
rabi_area=df.groupby('State Name')['RABI SORGHUM AREA (1000 ha)'].sum().sort_values(ascending=False).reset_index().head(10)

rabi_area

       State Name  RABI SORGHUM AREA (1000 ha)
0     Maharashtra                    169314.99
1       Karnataka                     65646.28
2       Telangana                     21712.25
3  Andhra Pradesh                     13523.62
4      Tamil Nadu                      5327.94
5         Gujarat                      5067.82
6  Madhya Pradesh                       130.49
7    Chhattisgarh                        28.11
8       Rajasthan                         4.64
9           Bihar                         0.13

In [10]:
fig = px.bar(rabi_area, x='State Name', y='RABI SORGHUM AREA (1000 ha)',
             title='Total Rabi Sorghum Area by Top 10 states',
             labels={'State Name': 'State Name', 'RABI SORGHUM AREA (1000 ha) ': 'RABI SORGHUM AREA (1000 ha)'},
             color='RABI SORGHUM AREA (1000 ha)', color_continuous_scale='magma'
          )

fig.update_layout(xaxis_title='State names', yaxis_title='Rabi Sorghum  Area')

fig.update_layout(template='plotly_white')
fig.update_layout(height=600,width=800)
fig.show()

<b><span style="color: #3C0753; background-color:#DF826C; padding: 20px; font-size: 18px; border-left: 8px solid F037A5">ii) By production</span></b>

In [11]:
rabi_pro=df.groupby('State Name')['RABI SORGHUM PRODUCTION (1000 tons)'].sum().sort_values(ascending=False).reset_index().head(10)

rabi_pro

       State Name  RABI SORGHUM PRODUCTION (1000 tons)
0     Maharashtra                             85454.84
1       Karnataka                             42753.83
2       Telangana                             11949.33
3  Andhra Pradesh                             11386.80
4      Tamil Nadu                              5532.34
5         Gujarat                              4333.60
6  Madhya Pradesh                               116.69
7    Chhattisgarh                                27.30
8     West Bengal                                 0.02
9       Jharkhand                                 0.00

In [20]:
fig = px.pie(rabi_pro, names='State Name', values='RABI SORGHUM PRODUCTION (1000 tons)',
             title='Total Rabi Sorghum production by top 10 states',
             labels={'State Name': 'State Name', 'RABI SORGHUM PRODUCTION (1000 tons)': 'RABI SORGHUM PRODUCTION (1000 tons)'},
             color='RABI SORGHUM PRODUCTION (1000 tons)',color_discrete_sequence=px.colors.sequential.Magma 
            )

fig.update_layout(template='plotly_white')
fig.update_layout(height=600,width=800)
fig.show()

<b><span style="color: #3C0753; background-color:#DF826C; padding: 20px; font-size: 18px; border-left: 8px solid F037A5">iii) By yield</span></b>

In [106]:
rabi_yield=df.groupby('State Name')['RABI SORGHUM YIELD (Kg per ha)'].sum().sort_values(ascending=False).reset_index().head(10)

rabi_yield

       State Name  RABI SORGHUM YIELD (Kg per ha)
0       Karnataka                       681187.26
1      Tamil Nadu                       653370.09
2     Maharashtra                       629022.21
3  Andhra Pradesh                       616195.65
4         Gujarat                       526947.04
5       Telangana                       312354.51
6  Madhya Pradesh                       213348.99
7    Chhattisgarh                        10062.61
8     West Bengal                          666.67
9       Jharkhand                            0.00

In [39]:
fig = px.scatter(
    rabi_yield,
    x="State Name",
    y="RABI SORGHUM YIELD (Kg per ha)",
    size="RABI SORGHUM YIELD (Kg per ha)",  
    color="RABI SORGHUM YIELD (Kg per ha)",  
    title="Rabi Sorghum Yield by top 10 states",
    size_max=30,
color_continuous_scale='Sunset')

fig.update_layout(
    height=600,
    width=800,
    xaxis_title="State Name",
    yaxis_title="Rabi Sorghum yield",
    showlegend=True,  
)
fig.update_layout(template='plotly_white')
fig.show()

<div style="background-color: #8ADAB2; #padding: 20px; border-radius: 20px;">
    <p style="font-size: 40px; font-family: 'Verdana'; color: #3A405A; text-align: center;">Maize</p>
</div>

<b><span style="color: #3C0753; background-color:#8ADAB2; padding: 20px; font-size: 18px; border-left: 8px solid F037A5">i) By area</span></b>

In [26]:
maize_ar=df.groupby('State Name')['MAIZE AREA (1000 ha)'].sum().sort_values(ascending=False).reset_index().head(10)

maize_ar

         State Name  MAIZE AREA (1000 ha)
0     Uttar Pradesh              55127.87
1         Rajasthan              47418.96
2    Madhya Pradesh              39046.69
3             Bihar              33619.25
4         Karnataka              26161.97
5         Telangana              20348.21
6           Gujarat              19253.28
7       Maharashtra              16378.97
8  Himachal Pradesh              14438.60
9            Punjab              14140.12

In [60]:
fig = px.bar(maize_ar, x='State Name', y='MAIZE AREA (1000 ha)',
             title='Total Maize Area by Top 10 states',
             labels={'State Name': 'State Name', 'MAIZE AREA (1000 ha) ': 'MAIZE AREA (1000 ha)'},
             color='MAIZE AREA (1000 ha)', color_continuous_scale='sunset'
          )

fig.update_layout(xaxis_title='State names', yaxis_title='Maize  Area')

fig.update_layout(template='ggplot2')
fig.update_layout(height=600,width=800)
fig.show()

<b><span style="color: #3C0753; background-color:#8ADAB2; padding: 20px; font-size: 18px; border-left: 8px solid F037A5">ii) By production</span></b>

In [29]:
maize_pro=df.groupby('State Name')['MAIZE PRODUCTION (1000 tons)'].sum().sort_values(ascending=False).reset_index().head(10)

maize_pro

         State Name  MAIZE PRODUCTION (1000 tons)
0         Karnataka                      75586.69
1             Bihar                      67137.23
2     Uttar Pradesh                      63772.89
3    Madhya Pradesh                      58764.11
4         Telangana                      55766.72
5         Rajasthan                      54303.17
6       Maharashtra                      35862.71
7  Himachal Pradesh                      28075.97
8            Punjab                      27317.20
9    Andhra Pradesh                      25242.65

In [58]:
fig = px.pie(maize_pro, names='State Name', values='MAIZE PRODUCTION (1000 tons)',
             title='Total Maize production by top 10 states',
             labels={'State Name': 'State Name', 'MAIZE PRODUCTION (1000 tons)': 'MAIZE PRODUCTION (1000 tons)'},
             color='MAIZE PRODUCTION (1000 tons)',
             hole=0.1
             #color_discrete_sequence=px.colors.sequential.Sunset
            )

fig.update_layout(template='plotly_dark')
fig.update_layout(height=600,width=800)
fig.show()

<b><span style="color: #3C0753; background-color:#8ADAB2; padding: 20px; font-size: 18px; border-left: 8px solid F037A5">iii) By yield</span></b>

In [54]:
maize_yield=df.groupby('State Name')['MAIZE YIELD (Kg per ha)'].sum().sort_values(ascending=False).reset_index().head(10)

maize_yield

       State Name  MAIZE YIELD (Kg per ha)
0   Uttar Pradesh               2671858.82
1       Karnataka               2578249.56
2  Madhya Pradesh               2364175.31
3  Andhra Pradesh               1787444.16
4     Maharashtra               1737245.65
5     West Bengal               1226410.67
6          Punjab               1184457.16
7       Rajasthan               1138733.84
8      Tamil Nadu               1128312.96
9       Telangana               1094275.13

In [57]:
import plotly.express as px

fig = px.scatter(
    maize_yield,
    x="State Name",
    y="MAIZE YIELD (Kg per ha)",
    size="MAIZE YIELD (Kg per ha)",
    color="MAIZE YIELD (Kg per ha)",
    title="MAIZE YIELD (Kg per ha)",
    size_max=30,
    color_continuous_scale='Viridis'  # Specify the color scale
)

fig.update_layout(
    height=600,
    width=800,
    xaxis_title="State Name",
    yaxis_title="Maize yield",
    showlegend=True,
)
fig.update_layout(template='plotly_dark')
fig.show()

<div style="background-color: #E6A4B4; #padding: 20px; border-radius: 20px;">
    <p style="font-size: 40px; font-family: 'Verdana'; color: #3A405A; text-align: center;">Finger Millet</p>
</div>

<b><span style="color: #3C0753; background-color:#E6A4B4; padding: 20px; font-size: 18px; border-left: 8px solid F037A5">i) By area</span></b>

In [61]:
fg_area=df.groupby('State Name')['FINGER MILLET AREA (1000 ha)'].sum().sort_values(ascending=False).reset_index().head(10)

fg_area

       State Name  FINGER MILLET AREA (1000 ha)
0       Karnataka                      49839.37
1          Orissa                      10853.31
2      Tamil Nadu                       9463.54
3     Maharashtra                       9117.78
4  Andhra Pradesh                       6659.47
5     Uttarakhand                       4528.63
6       Jharkhand                       2578.99
7           Bihar                       2319.19
8       Telangana                       1899.97
9         Gujarat                       1853.80

In [64]:
fig = px.bar(fg_area, x='State Name', y='FINGER MILLET AREA (1000 ha)',
             title='Total Finger Millet Area by Top 10 states',
             labels={'State Name': 'State Name', 'FINGER MILLET AREA (1000 ha) ': 'FINGER MILLET AREA (1000 ha)'},
             color='FINGER MILLET AREA (1000 ha)', color_continuous_scale='blackbody'
          )

fig.update_layout(xaxis_title='State names', yaxis_title='Finger Millet Area')

fig.update_layout(template='seaborn')
fig.update_layout(height=600,width=800)
fig.show()

<b><span style="color: #3C0753; background-color:#E6A4B4; padding: 20px; font-size: 18px; border-left: 8px solid F037A5">ii) By production</span></b>

In [65]:
fg_pro=df.groupby('State Name')['FINGER MILLET PRODUCTION (1000 tons)'].sum().sort_values(ascending=False).reset_index().head(10)

fg_pro

       State Name  FINGER MILLET PRODUCTION (1000 tons)
0       Karnataka                              63473.92
1      Tamil Nadu                              14514.43
2          Orissa                               8654.58
3     Maharashtra                               8547.30
4  Andhra Pradesh                               7470.99
5     Uttarakhand                               5263.17
6           Bihar                               1654.19
7       Jharkhand                               1487.70
8         Gujarat                               1475.66
9       Telangana                               1247.89

In [70]:
fig = px.pie(fg_pro, names='State Name', values='FINGER MILLET PRODUCTION (1000 tons)',
             title='Total Finger Millet production by top 10 states',
             labels={'State Name': 'State Name', 'FINGER MILLET PRODUCTION (1000 tons)': 'FINGER MILLET PRODUCTION (1000 tons)'},
             color='FINGER MILLET PRODUCTION (1000 tons)',
             hole=0.1,
             color_discrete_sequence=px.colors.sequential.Plasma
            )

fig.update_layout(template='seaborn')
fig.update_layout(height=600,width=800)
fig.show()

<b><span style="color: #3C0753; background-color:#E6A4B4; padding: 20px; font-size: 18px; border-left: 8px solid F037A5">iii) By yield</span></b>

In [71]:
fg_yi=df.groupby('State Name')['FINGER MILLET YIELD (Kg per ha)'].sum().sort_values(ascending=False).reset_index().head(10)

fg_yi

       State Name  FINGER MILLET YIELD (Kg per ha)
0      Tamil Nadu                        956679.41
1       Karnataka                        911161.55
2  Andhra Pradesh                        663291.88
3     Maharashtra                        534197.51
4          Orissa                        448949.97
5           Bihar                        417987.30
6     Uttarakhand                        341901.79
7   Uttar Pradesh                        301879.29
8          Kerala                        221738.38
9         Gujarat                        216492.07

In [74]:
fig = px.scatter(
    fg_yi,
    x="State Name",
    y="FINGER MILLET YIELD (Kg per ha)",
    size="FINGER MILLET YIELD (Kg per ha)",
    color="FINGER MILLET YIELD (Kg per ha)",
    title="Finger Millet yield by top 10 states",
    size_max=30,
    color_continuous_scale='Magma' 
)

fig.update_layout(
    height=600,
    width=800,
    xaxis_title="State Name",
    yaxis_title="Finger Millet yield",
    showlegend=True,
)
fig.update_layout(template='seaborn')
fig.show()

<div style="background-color: #9BB8CD; #padding: 20px; border-radius: 20px;">
    <p style="font-size: 40px; font-family: 'Verdana'; color: #3A405A; text-align: center;">Safflower</p>
</div>

<b><span style="color: #3C0753; background-color:#9BB8CD; padding: 20px; font-size: 18px; border-left: 8px solid F037A5">i) By area</span></b>

In [75]:
saff_ar=df.groupby('State Name')['SAFFLOWER AREA (1000 ha)'].sum().sort_values(ascending=False).reset_index().head(10)

saff_ar

       State Name  SAFFLOWER AREA (1000 ha)
0     Maharashtra                  19730.00
1       Karnataka                   6929.85
2       Telangana                   1016.09
3  Andhra Pradesh                    343.28
4          Orissa                    111.13
5           Assam                    100.21
6  Madhya Pradesh                     98.48
7    Chhattisgarh                     31.54
8         Gujarat                     18.70
9           Bihar                     17.85

In [81]:
fig = px.bar(saff_ar, x='State Name', y='SAFFLOWER AREA (1000 ha)',
             title='Total Safflower Area by Top 10 states',
             labels={'State Name': 'State Name', 'SAFFLOWER AREA (1000 ha) ': 'SAFFLOWER AREA (1000 ha)'},
             color='SAFFLOWER AREA (1000 ha)', color_continuous_scale='aggrnyl'
          )

fig.update_layout(xaxis_title='State names', yaxis_title='Safflower Area')

fig.update_layout(template='simple_white')
fig.update_layout(height=600,width=800)
fig.show()

<b><span style="color: #3C0753; background-color:#9BB8CD; padding: 20px; font-size: 18px; border-left: 8px solid F037A5">ii) By production</span></b>

In [80]:
saff_pro=df.groupby('State Name')['SAFFLOWER PRODUCTION (1000 tons)'].sum().sort_values(ascending=False).reset_index().head(10)

saff_pro

       State Name  SAFFLOWER PRODUCTION (1000 tons)
0     Maharashtra                           8151.93
1       Karnataka                           3081.32
2       Telangana                            299.43
3  Andhra Pradesh                            108.41
4           Assam                             39.39
5  Madhya Pradesh                             35.44
6         Gujarat                              7.80
7    Chhattisgarh                              7.48
8     West Bengal                              5.06
9         Haryana                              0.00

In [91]:
fig = px.pie(
    saff_pro,
    names='State Name',
    values='SAFFLOWER PRODUCTION (1000 tons)',
    title='Total Safflower production by top 10 states',
    labels={'State Name': 'State Name', 'SAFFLOWER PRODUCTION (1000 tons)': 'SAFFLOWER PRODUCTION (1000 tons)'},
    color='SAFFLOWER PRODUCTION (1000 tons)'
)
# Manually adjust the pull to make all slices fully visible
fig.update_traces(pull=[0] * len(saff_pro), textinfo='value+percent', textposition='inside')

fig.update_layout(template='simple_white')
fig.update_layout(height=600, width=800)
fig.show()

<b><span style="color: #3C0753; background-color:#9BB8CD; padding: 20px; font-size: 18px; border-left: 8px solid F037A5">iii) By yield</span></b>

In [92]:
saff_yi=df.groupby('State Name')['SAFFLOWER YIELD (Kg per ha)'].sum().sort_values(ascending=False).reset_index().head(10)

saff_yi

       State Name  SAFFLOWER YIELD (Kg per ha)
0     Maharashtra                    390781.65
1       Karnataka                    244414.53
2       Telangana                    106794.21
3           Assam                     91607.02
4          Orissa                     78098.90
5  Madhya Pradesh                     59071.70
6  Andhra Pradesh                     57231.16
7     West Bengal                     56045.94
8           Bihar                     36215.46
9    Chhattisgarh                     34755.97

In [96]:
fig = px.scatter(
    saff_yi,
    x="State Name",
    y="SAFFLOWER YIELD (Kg per ha)",
    size="SAFFLOWER YIELD (Kg per ha)",
    color="SAFFLOWER YIELD (Kg per ha)",
    title="Safflower yield by top 10 states",
    size_max=30,
    color_continuous_scale='Tealgrn' 
)

fig.update_layout(
    height=600,
    width=800,
    xaxis_title="State Name",
    yaxis_title="Finger Millet yield",
    showlegend=True,
)
fig.update_layout(template='simple_white')
fig.show()

<div style="background-color:  #FFF8C9; #padding: 20px; border-radius: 20px;">
    <p style="font-size: 40px; font-family: 'Verdana'; color: #3A405A; text-align: center;">Sugercane</p>
</div>

<b><span style="color: #3C0753; background-color:#FFF8C9; padding: 20px; font-size: 18px; border-left: 8px solid F037A5">i) By area</span></b>

In [97]:
sug_ar=df.groupby('State Name')['SUGARCANE AREA (1000 ha)'].sum().sort_values(ascending=False).reset_index().head(10)

sug_ar

       State Name  SUGARCANE AREA (1000 ha)
0   Uttar Pradesh                  93073.41
1     Maharashtra                  24847.84
2       Karnataka                  14002.22
3      Tamil Nadu                  11949.53
4  Andhra Pradesh                   8428.76
5         Gujarat                   7389.78
6         Haryana                   6817.17
7           Bihar                   6750.22
8          Punjab                   5531.39
9  Madhya Pradesh                   2908.57

In [100]:
fig = px.bar(sug_ar, x='State Name', y='SUGARCANE AREA (1000 ha)',
             title='Total Sugercane Area by Top 10 states',
             labels={'State Name': 'State Name', 'SUGARCANE AREA (1000 ha) ': 'SUGARCANE AREA (1000 ha)'},
             color='SUGARCANE AREA (1000 ha)', color_continuous_scale='rainbow'
          )

fig.update_layout(xaxis_title='State names', yaxis_title='Sugercane Area')

fig.update_layout(template='ggplot2')
fig.update_layout(height=600,width=800)
fig.show()

<b><span style="color: #3C0753; background-color:#FFF8C9; padding: 20px; font-size: 18px; border-left: 8px solid F037A5">ii) By production</span></b>

In [101]:
sug_pro=df.groupby('State Name')['SUGARCANE PRODUCTION (1000 tons)'].sum().sort_values(ascending=False).reset_index().head(10)

sug_pro

       State Name  SUGARCANE PRODUCTION (1000 tons)
0   Uttar Pradesh                         506242.87
1     Maharashtra                         206132.30
2      Tamil Nadu                         123795.81
3       Karnataka                         115747.19
4  Andhra Pradesh                          54046.62
5         Gujarat                          51672.90
6         Haryana                          34767.80
7          Punjab                          31488.18
8           Bihar                          28589.73
9       Telangana                          15776.15

In [102]:
fig = px.pie(sug_pro, names='State Name', values='SUGARCANE PRODUCTION (1000 tons)',
             title='Total Sugercane production by top 10 states',
             labels={'State Name': 'State Name', 'SUGARCANE PRODUCTION (1000 tons)': 'SUGARCANE PRODUCTION (1000 tons)'},
             color='SUGARCANE PRODUCTION (1000 tons)',
             hole=0.1,
             color_discrete_sequence=px.colors.sequential.Blackbody
            )

fig.update_layout(template='ggplot2')
fig.update_layout(height=600,width=800)
fig.show()

<b><span style="color: #3C0753; background-color:#FFF8C9; padding: 20px; font-size: 18px; border-left: 8px solid F037A5">iii) By yield</span></b>

In [103]:
sug_yi=df.groupby('State Name')['SUGARCANE YIELD (Kg per ha)'].sum().sort_values(ascending=False).reset_index().head(10)

sug_yi

       State Name  SUGARCANE YIELD (Kg per ha)
0   Uttar Pradesh                  11211541.16
1     Maharashtra                   8659716.95
2       Karnataka                   7790993.02
3      Tamil Nadu                   5409871.60
4         Gujarat                   4863621.56
5  Madhya Pradesh                   4784838.16
6     West Bengal                   4479474.06
7          Orissa                   4134958.23
8  Andhra Pradesh                   4108210.73
9       Rajasthan                   4091030.10

In [105]:
fig = px.scatter(
    sug_yi,
    x="State Name",
    y="SUGARCANE YIELD (Kg per ha)",
    size="SUGARCANE YIELD (Kg per ha)",
    color="SUGARCANE YIELD (Kg per ha)",
    title="Sugarcane yield by top 10 states",
    size_max=30,
     
)

fig.update_layout(
    height=600,
    width=800,
    xaxis_title="State Name",
    yaxis_title="Finger Millet yield",
    showlegend=True,
)
fig.update_layout(template='ggplot2')
fig.show()

<div style="background-color: #F2F3F4; padding: 20px; border-radius: 10px;">
    <p style="font-size: 24px; font-family: 'Verdana'; color: #3A405A; text-align: center;">
Thank you for exploring my notebook!</p>
</div>